Task2
97th/tasks pull request #2
Opened 2021-12-24 07:58 UTC by 97th

2021-12-28 02:43 UTC, ova777 requested changes
Нужно переделать функцию что бы она возвращала true/false (как по условию задачи), и поправить codestyle по PSR.

2021-12-28 02:43 UTC, ova777 commented on task2.powerOfThree.php
> +function isPowerOfThree(int $number)
По условию задачи, функция должна возвращать true или false.
У тебя же функция выводит результат на экран, и всегда возвращает true (т.к. print_r - это функция которая возвращает true).

2021-12-28 02:43 UTC, ovaunit commented on task2.powerOfThree.php
> +    {
По PSR открывающая скобка на новой строке должна быть только у функций, методов, классов, в остальных случаях - перенос не нужен. Соответственно это также относится к for.

2021-12-28 02:43 UTC, ova777 commented on task2.powerOfThree.php
> +        return print_r('true 3^0'.PHP_EOL);
Все операторы (такие как конкатенация, арифметические операции, сравнения) - должны выделяться пробелами с двух сторон. Т.е. здесь должно быть: `'true 3^0' . PHP_EOL`

2021-12-28 02:43 UTC, ovaunit commented on task2.powerOfThree.php
> +    for ($i=1;$i<100;$i++)
Операторы нужно выделить пробелами, и после символа `;` также должны быть пробелы.

2021-12-28 02:43 UTC, ova777 commented on task2.powerOfThree.php
> +        $result = pow($number, (1/$i));
Знак деления нужно выделить пробелами с двух сторон

2021-12-28 08:42 UTC, ova777 requested changes
Интересное решение! Но нужно еще немного доработать.

2021-12-28 08:42 UTC, ova777 commented on task2.powerOfThree.php
> +    if ($number == 1){
Не хватает пробела перед фигурной скобкой.
Также лучше всегда всегда делать строгое сравнение (`===`), кроме случаев когда явно нужно нестрогое.

2021-12-28 08:42 UTC, ova777 commented on task2.powerOfThree.php
> +    for ($i = 1; $i < 100; $i++){
Не хватает пробела перед фигурной скобкой

2021-12-28 08:42 UTC, ova777 commented on task2.powerOfThree.php
> +        if ($result == 3){
Лучше сделать строгое сравнение, и не хватает пробела перед фигурной скобкой.

2022-01-10 05:42 UTC, ova777 requested changes
В данный момент функция работает неправильно

2022-01-10 05:42 UTC, ova777 commented on task2.powerOfThree.php
> +    if ($number == 1) {
Лучше сделать строгое сравнение, как ты это делаешь для сравнения `$result`

2022-01-10 05:42 UTC, ova777 commented on task2.powerOfThree.php
> +        if ($result === 3) {
Для $number = 9 функция вернет false, хотя это степень тройки.
Происходит это потому что функция pow возвращает float, а сравниваем мы $result с int'ом.
Но pow также может вернуть и int. Поэтому это сравнение нужно доработать, что бы всегда float сравнивался с float'ом:
```
if ((float)$result === 3.0) {
```

2022-01-10 05:42 UTC, ova777 requested changes
В данный момент функция работает неправильно

2022-01-10 06:14 UTC, ova777 approved these changes

2022-01-11 02:00 UTC, closed without merging